### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by jatocode** [muffinista/chatterbot#10]
Since a couple of weeks I get constant "Rate limit exceeded errors".

Seems like a call to "replies" is enough to trigger this, even without actually having any replies waiting?

Edit: The code for my bot can be seen here: https://github.com/jatocode/pequenoTweeter/blob/master/pequenoTweeter.rb

**Comment by hassanshaikley** [comment]
Do they release specific numbers on rate limitng? OR do you guys have any rules of thumb?

It seems my rate decreases every day.
