### ISSUE TITLE
Follow / unfollow users

### ISSUE THREAD

**Issue by mrded** [muffinista/chatterbot#25]
Can the bot follow and unfollow user?

Thanks.

**Comment by muffinista** [comment]
Following is easy, but depends on if your using streaming or not. If you're not using streaming it would be like this:

```
follow tweet.user
```

Chatterbot doesn't directly support unfollowing right now, but you could do it by accessing the underlying Twitter client, and it would look like:

```
client.unfollow tweet.user
```

**Comment by mrded** [comment]
Great, thank you
