### ISSUE TITLE
Can an app get banned?

### ISSUE THREAD

**Issue by hassanshaikley** [muffinista/chatterbot#31]
My app no longer seems to work anymore. Does anyone know about this happening and how to avoid it?

**Comment by muffinista** [comment]
An app can most definitely be banned. I recommend checking out the API terms of use here https://dev.twitter.com/overview/terms and seeing how they apply. In particular, @-mentioning an account that hasn't opted in to the experience is almost certainly going to get you banned.

**Comment by RyanTG** [comment]
@muffinista I don't want to start a new issue for my question, and it's related to this. My bot is doing a search and reply, and each time I run it, I would like to choose how many users it replies to (say, just 1 or 2). How would I do that, based on this code:

`replies do |tweet|
  reply "#USER# Thanks for contacting me!", tweet
end`

Thanks :)
