### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by 34code** [muffinista/chatterbot#36]
```Users/buzz/.rvm/gems/ruby-2.2.0/gems/chatterbot-1.0.1/lib/chatterbot/tweet.rb:29:in `reply': [DEPRECATION] #[:id] is deprecated. Use #id to fetch the value.```

I'm using streaming with the reply functionality. I would love to take a stab at fixing it.. where should i look?

**Comment by muffinista** [comment]
There's a good chance this is already fixed in master, I've been cleaning these up bit-by-bit. Basically any reference to `tweet[:id]` needs to be replaced with `tweet.id`.

**Comment by staringispolite** [comment]
Great bot builder! I recently forked from master and this is still here (tweet.rb:29). Just FYI. Keep up the great work

**Comment by muffinista** [comment]
This is in master now, I wrote the code and never committed it :(

**Comment by prestonmcp** [comment]
Some reason I am still getting the same error as OP
