### ISSUE TITLE
401 when streaming. Oauth_timestamp?

### ISSUE THREAD

**Issue by Corstiaan84** [muffinista/chatterbot#39]
Hi,

Love this project :-).

I am seeing this errors trying to stream: /.rvm/gems/ruby-2.2.1/gems/twitter-5.14.0/lib/twitter/rest/response/raise_error.rb:15:in `on_complete': Could not authenticate you. (Twitter::Error::Unauthorized)

I have done some research and I think it's due to the oauth timestamp. My system clock seems to be in sync though. Credentials must be ok since everything else is working...

Ideas? :-)

Thanks!

**Comment by muffinista** [comment]
Hey, can you give me an idea of exactly when this happens? Also, does it happen consistently, etc? And a full backtrace might be helpful. Thanks!

**Comment by Corstiaan84** [comment]
Hey, yes it happens consistently. Here's the trace: https://gist.github.com/Corstiaan84/c70324d47c9fb129a512

Thanks!

**Comment by muffinista** [comment]
Sorry for the delay. Are you able to post the code for your bot, with credentials/etc removed? If you want you can email it to me -- colin at muffinlabs dot com

**Comment by wr** [comment]
I'm experiencing the same error when using the Streaming API:

```
orker.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/chatterbot-1.0.1/lib/chatterbot/dsl.rb:67:in `streaming'
```

Happens consistently – but chatterbot works fine when using the non-streaming APIs with the exact same credentials.

Using the sample code here:

```
#
# run a search
#
streaming(endpoint:"search") do
    search("Streaming API") do |tweet|
      puts tweet.text
    end
end
```

**Comment by muffinista** [comment]
OK, I think you might need to try this:
```
streaming(endpoint: :filter) do
  search("Streaming API") do |tweet|
    puts tweet.text
  end
end
```

(note the different endpoint).

This functionality has changed a bit in the next version of the gem but I haven't released a new version quite yet, but you can also try running against the master branch of git if that's an option for you.

**Comment by Corstiaan84** [comment]
@muffinista, your solutions seems to work :-).

However, when running this:
```
streaming(endpoint: :filter) do
    search("obama") do |tweet|
      puts tweet.text
    end
end
```
this is the output of the stream:
```
#<Twitter::Tweet:0x007f8c9a567ab0>
RT @cbatson941: DEAR OBAMA: DAY 7 OF OPEN CARRY IN TEXAS. NO SHOOTOUTS IN STREETS. CAN YOU SAY THE SAME ABOUT YOUR HOMETOWN?
#<Twitter::Tweet:0x007f8c9a565f80>
#<Twitter::Tweet:0x007f8c9a564298>
#<Twitter::Tweet:0x007f8c9a56f148>
#<Twitter::Tweet:0x007f8c9a56c380>
RT @nice_mustard: 2017: obama has taken all the guns. i trudge through a desolate hellscape of alive unshot people. "WHY???" i scream at a …
#<Twitter::Tweet:0x007f8c9a9bb0d0>
@SchneiderSTLMO It's offensive trying to blame good citizens for evil gun actions! I find Obama offensive period &amp; his agenda too♡
#<Twitter::Tweet:0x007f8c9a9b83f8>
#<Twitter::Tweet:0x007f8c9c2b6f58>
@TXhighplains @theblaze He gets contempt for using the N word but Moochelle Obama openly says white people is what's wrong with America.
#<Twitter::Tweet:0x007f8c9c2b42f8>
RT @princesssnena: Can Obama jus stay president again? 😂
#<Twitter::Tweet:0x007f8c9a9c5a80>
#<Twitter::Tweet:0x007f8c9bbe3d48>
#<Twitter::Tweet:0x007f8c9a57e800>
#<Twitter::Tweet:0x007f8c9a585b78>
#<Twitter::Tweet:0x007f8c9a58f538>
RT @nice_mustard: 2017: obama has taken all the guns. i trudge through a desolate hellscape of alive unshot people. "WHY???" i scream at a …
#<Twitter::Tweet:0x007f8c9a58c3b0>
#<Twitter::Tweet:0x007f8c9a9d2fc8>
Kerry says #NorthKorea was never less unattended by Obama foreign policy, says his spox will take all Qs on it
#<Twitter::Tweet:0x007f8c9a9d12e0>
#<Twitter::Tweet:0x007f8c9a595488>
```
Is is correct that I am not see the text of every tweet?

**Comment by wr** [comment]
seems to work for me as well :)

**Comment by muffinista** [comment]
There's a few possibilities here:
- I think this version chatterbot skips retweets by default, but it will instantiate the tweet before deciding to reject it
- If you have a blacklist in place, those tweets will also be instantiated but skipped. 

If it seems like something else, let me know, but probably under a new issue, since I think we solved this one. Thanks!

**Comment by Corstiaan84** [comment]
Seems legit :-)
