### ISSUE TITLE
chatterbot-register no such file or directory

### ISSUE THREAD

**Issue by Pimentoso** [muffinista/chatterbot#40]
Hi, chatterbot-register.rb fails on line 72 trying to rename the config file that doesn't exist yet.
I don't know if it's the right way of running the script but I simply copied it into the folder where I wanted my skeleton and ran it.

Error is 
`chatterbot-register.rb:72:in 'rename': No such file or directory @ sys_fail2 - (/Users/xxx/Workspace/bot/tmp_bot_name.yml, /Users/xxx/Workspace/bot/accountname.yml) (Errno::ENOENT)`

I solved it by making it actually write the config file before the rename, I can issue a pull request if needed.

Thanks.

**Comment by muffinista** [comment]
Hey, a PR would be more than welcome. Did you install the gem/etc? If so, you should be able to run `chatterbot-register` from wherever you like.

**Comment by Pimentoso** [comment]
Right, issue does not happen installing gem and running the command from any folder. I must have set a different local ruby version (without the gem) inside the folder I was working in and the shell did not recognize the executable. Closing this. Thanks!

**Comment by Ico8B** [comment]
[Errno 2] No such file or directory

This messenger compare after I write command 

python chatterbot_<name>.py

I work with Atom, and the directory exists.

**Comment by Ico8B** [comment]
hello, I followed the tutorial on the official website. It gives me error
on string "database". Syntax error. I do not understand why

Il gio 29 nov 2018, 21:24 Colin Mitchell <notifications@github.com> ha
scritto:

**Comment by muffinista** [comment]
@Ico8B I'm going to need you to give me a lot more detail about exactly what you're doing, and the full output you get.
