### ISSUE TITLE
Attaching Pic to Tweet/Direct Message

### ISSUE THREAD

**Issue by arnoldfungai** [muffinista/chatterbot#46]
Hi @muffinista, your work is much appreciated. Using it successfully @opentxtbook (beta).
My question is Chatterbot able to attach `jpeg/png` to a `tweet/direct message`?

**Comment by muffinista** [comment]
Hi, thanks! You can attach an image to a tweet like this:

```
tweet "hello!", media:"/path/to/file.jpg"
```

I only just released a version of the gem which supports this, so you might need to update.

Unfortunately, Twitter doesn't provide API support for attaching an image to a DM (@see https://twittercommunity.com/t/uploading-images-in-dms/12317/8)

**Comment by arnoldmarunda** [comment]
@muffinista I'm trying to attach an image to a reply
`reply "This is my reply", media:"/path/to/file.jpg", tweet`

1. What is the correct syntax to attach and image to a reply?
2. Is it possible to have the image retrieved from a URL instead of filesystem?

**Comment by muffinista** [comment]
1) I think you need to call it like this:

```
reply "This is my reply", tweet, media:"/path/to/file.jpg"
```

2) The Twitter API doesn't support this. I might consider a PR that added it to chatterbot, but it's a bit of a security risk. It's also not too difficult to write a method that downloads a URL to your local filesystem, then use that file when you call `reply`

**Comment by arnoldmarunda** [comment]
@muffinista - you 'ultra efficient!!'. If I ever make big money - will certainly remember you!! 

Did not understand what you mean by "consider a PR".

**Comment by muffinista** [comment]
Thanks! 

PR is short for pull request. Basically I mean that if someone wants to add that functionality to chatterbot, and submits a PR with the changes, I would consider adding it to the library, but I probably won't write it myself.
