### ISSUE TITLE
Breaking out of nested direct_messages block

### ISSUE THREAD

**Issue by arnoldfungai** [muffinista/chatterbot#47]
Hello @muffinista 

I have created a nested level 2 `direct_messages `block. Any ideas on how I would break out of it, and return to the level 1 `direct_messages `block.

Using `break` I get the error message;
``block (2 levels) in <main>': break from proc-closure (LocalJumpError)`

**Comment by muffinista** [comment]
I have a feeling that's going to be impossible, but can you maybe post a code snippet just in case?

**Comment by arnoldfungai** [comment]
Thanks @muffinista for taking a look at the code, much appreciated. 

I am really new at Ruby - just integrating code and hacking away. So feel free to suggest other ways where I am doing it wrong. 

I need a scenario where the user sends a level 1 direct message command e.g '!study 3' to chatterbot to evoke a study session with 3 questions. The  study session is in a nested level 2 direct_messages block. After the 3 study session questions are completed, the user is given their assessment and they break out of the study session. Then that the user continues with other chatterbot commands. 

In the code below actually has the break at level 3 block. **This is not the code that gave the error above.** I was trying to find another way. However, this code only breaks to level 2 after the , but not to level 1 as I require, 

I went this route because i understand chatterbot direct_messages to only allow the bot to respond to requests made by user i.e dm.sender. The study session has the bot making the requests to the user, who then responds.

I hope what I have said above makes sense. You can try this code with bot @opentxtbook by sending !study 2 command. You will experience what I have said above. 

The code snippet is as follows;

```
direct_messages do |dm|
text = dm.text
src = text.split(' ',2)
content = src[1].to_s.strip
command = src[0].to_s.strip.downcase

case command

when '!study'
 $inquiry = content.to_i

 direct_message "Let's attempt #{$inquiry} questions in this study.", dm.sender
  $a = 1

  def sample_if_needed(response)
    if response.is_a?(Array)
      response.sample
    else
      response
    end
  end

  YES = ['yes', 'yeah', 'yep', 'y', 'true', 'ok', 'okay', 'of course', 'always', 'absolutely', 'affirmative', 'amen', 'yea', 'certainly', 'definitely', 'naturally', 'surely', 'unquestionably']
  NO = ['no', 'nope', 'nah', 'n', 'false', 'not', 'never', 'negative', 'never']

  questions = YAML.load(File.read('questions.yml')).shuffle
  question_iterator = questions.each
  question = nil
  answered = true
  scores = Hash.new(0)

if answered
    answered = false
    question = question_iterator.next
    direct_message "#{$i}| #{sample_if_needed(question[:prompt])}", dm.sender
end

direct_messages do |dm|

    input = dm.text.downcase
    question[:options].each do |option|
    keywords = if option[:keywords].is_a?(Array)
                   option[:keywords]
                 elsif option[:keywords]
                   YES
                 else
                   NO
                 end
        if keywords.any? { |s| input.match(/\b#{s}\b/) }
        direct_message "#{sample_if_needed(option[:response])}", dm.sender
        option[:results].keys.each do |key|
          scores[key] += option[:results][key]

          end
          answered = true

          if answered
            question = question_iterator.next
              $a += 1
              if $a <= $inquiry
              direct_message "#{$a}| #{sample_if_needed(question[:prompt])}", dm.sender
            else
                direct_message "Your study performance, based on my assessement of the #{$inquiry} inquiries you attempted, are as follows;", dm.sender
                scores.each {|subject, grade| direct_message "#{subject}|#{grade}", dm.sender }
                break
              end
            end
        end
      end
      # Print question help, unless question answered
        direct_message "#{sample_if_needed(question[:help])}", dm.sender unless answered
        answered = false
  end
```

**Comment by arnoldfungai** [comment]
Hi sorry, @muffinista for being a bother. 
I realised there were serious problems with my code, as it was causing certain inconsistencies in Chatterbot. Will completely revisit. 

Will be closing issue.

**Comment by muffinista** [comment]
Ok good luck!
