### ISSUE TITLE
Search still showing retweets

### ISSUE THREAD

**Issue by RyanTG** [muffinista/chatterbot#48]
I think I'm doing this wrong. When I include skip_retweets, I still get retweets in the results. My function is a "search and reply"

hypothetical example:

    search("'lovely bones'", :skip_retweets => "true") do |tweet|
      reply "#USER# Lovely bones is a great book", tweet
    end

I also tried:
  skip_retweets:true
and
  :skip_retweets => true

Can you explain how to correctly skip retweets?

**2nd issue:** That search will bring up things like, "it is a lovely day today. my bones feel great."

Is there a way to only search the EXACT phrase?

Thanks.

**Comment by RyanTG** [comment]
Ah, this seems to work (got this by looking at the tests):

    search("'lovely bones'", :skip_retweets => "true") do |tweet|
      bot.exclude_retweets
      reply "#USER# Lovely bones is a great book", tweet
    end

I'll close this. But if you have a solution for how to only include the exact search phrase, let me know.

**Comment by RyanTG** [comment]
I think I got it. This is a search & reply that tweets three times and only to tweets that have the exact phrase.

    num_hits = 0

    search("'lovely bones'") do |tweet|
        ttext = @grammar.flatten("#origin#") //that's generates my phrase, using tracery
        bot.exclude_retweets
        ttweet = tweet.text
        if ttweet.include? "lovely bones"
          puts "it matches"
          reply "#USER# #{ttext}", tweet
          num_hits += 1
        end

      break if num_hits == 3

    end

Sorry, I'm not a good programmer. So this took me some time to figure out.

**Comment by muffinista** [comment]
This is basically how I handle this as well by the way. Twitter's exact phrase search works inconsistently so it's sometimes better to do that check yourself. Neat use of tracery btw!
