### ISSUE TITLE
Retween with comment

### ISSUE THREAD

**Issue by RyanTG** [muffinista/chatterbot#50]
I'd like to retweet and add a comment. According to this: https://twittercommunity.com/t/method-to-retweet-with-comment/35330/4 for this to work you should include the permalink of the tweet. Is there a simple way to get the permalink? I'm not seeing that in the documentation. Thanks!

**Comment by muffinista** [comment]
I might be mistaken, but I think the `Tweet` object has a `#url` method, so `tweet "here's my tweet #{tweet.url}"` would work -- but if I'm wrong, you might need to generate the URL yourself from the username/id

**Comment by RyanTG** [comment]
Delayed response, but for your and anyone else's info: your suggestion worked perfectly! thanks.
