### ISSUE TITLE
Place / Location for tweet or reply?

### ISSUE THREAD

**Issue by blindpenguin** [muffinista/chatterbot#52]
Hi,

is it possible to set a place or a location for reply or tweet?

The Bot i created needs to set a random location somewhere in the world. It's part of the joke, because it's a parody account of an game character. :) 

Thanks.

**Comment by muffinista** [comment]
It should be possible. Basically, if you do:

```
tweet "here i am", lat: foo, long: bar, display_coordinates: true
```

Those extra parameters are passed along to the [Twitter gem](https://github.com/sferik/twitter) that chatterbot just sits on top of. There's actually a few examples of [geocoding tweets](https://github.com/sferik/twitter/blob/master/examples/Update.md#update) in the docs for that gem.

That said, I haven't tried this myself, so if it's not working for you, definitely let me know.
