### ISSUE TITLE
New to this, any ideas how to use the docker?

### ISSUE THREAD

**Issue by markaswift** [muffinista/chatterbot#53]
Hi,

I've downloaded the docker from here:

https://hub.docker.com/r/rubygem/chatterbot/

When I run the docker it simply outputs a log stating the various command options and then ends. I don't suppose you have any ideas how I proceed?

I understand this is outside of normal issue tracking hence will not be offended if it's closed without comment :)

**Comment by muffinista** [comment]
Oh weird, I've never seen that before? It looks like some sort of auto-generated docker image?

I've used docker but not to run a bot, but it seems like something that might be handy, so if you explore that at all and want to write up how you went about it, adding it to the docs seems like a great idea.

**Comment by markaswift** [comment]
I agree, it would be a superb way of using Chatterbot, that said, right now I'm just banging my head off the table trying to get it working...

**Comment by markaswift** [comment]
@muffinista progress... I have it running, the issue is that during various stages of the setup it wants to open a browser window when enter is hit, this causes the docker to crap out as I guess it's unable to find certain commands? Is it possible to skip that part?

**Comment by muffinista** [comment]
Yeah, you could generate the auth config manually, or outside of docker, but I'm noticing that the entrypoint in the Dockerfile is `chatterbot-register` which will restart the registration process whenever it's run I think? So this docker setup might not actually work at all.
