### ISSUE TITLE
only_interact_with_following ?

### ISSUE THREAD

**Issue by RyanTG** [muffinista/chatterbot#61]
I’m hoping to only retweet users that my account is following. Is there anything akin to `only_interact_with_following`?

More details: I’ll search for phrases and then retweet results, but I only want my results to have accounts that I’m following (I don’t care if they’re following me). 

Thanks.

**Comment by RyanTG** [comment]
Ah, I guess I just need to search home_timeline! Duh...

**Comment by RyanTG** [comment]
Actually, if you have any input on the syntax for searching only within your timeline, I'd appreciate the help. Or if it's not possible, that would be helpful to know, too!

**Comment by muffinista** [comment]
Sorry for the delay! It probably depends on exactly what you want to do, but I think you could do something like 

```
search("pizza") do |tweet| 
  do_stuff if interact_with_user?(tweet)
end
```

tbh I don't use this library much anymore, so there's a chance this won't work, sorry!

**Comment by RyanTG** [comment]
No sweat about any delay! thanks for responding.

I didn't realize `interact_with_user` was an option :smile: 
I'll play around with this.

I'm taking some ruby courses so I can get more sophisticated with my bots, and maybe advance to directly using the twitter gem. But for now, yours has allowed me to make a handful of fun ones with minimal ruby knowledge. thanks!

Also, I might submit a PR. One of your examples on the readme is now forbidden. Bots can't favorite tweets anymore :frowning_face:
