### ISSUE TITLE
Bot replies to same Tweet every time script runs

### ISSUE THREAD

**Issue by amrit** [muffinista/chatterbot#8]
How do I make sure the bot doesn't reply to the same tweet every time?

The following loop replies to tweets it has already replied to each time the script runs.

``` ruby
replies do |tweet|
  reply "Hi #USER#, thanks for your interest.", tweet
end
```

**Comment by staringispolite** [comment]
@muffinista I have this same problem. I assume it's because the bot's config isn't written to file or DB like you said above. How would I configure that? (Sorry if this is a standard Ruby thing - not new to programming, but new to Ruby)

**Comment by muffinista** [comment]
Glad you got it working! I actually removed db support in the 2.0 version of chatterbot -- it was difficult to use and maintain.

**Comment by staringispolite** [comment]
@muffinista Neat! Does it persist to the YML file in 2.0? I'd actually prefer that IMHO, just couldn't see how to get that working.
